### ISSUE TITLE
Doesn't work for Deltasol SLT (with ethernet option)

### ISSUE THREAD

**Issue by ramack** [ramack/openhab2-addons#1]
Fernando_Redondo reported [here](https://community.openhab.org/t/new-binding-resol-vbus/2203/68) that the plugin doesn't work with the exception:
```
Jan  7 00:29:29 OpenHAB karaf[27808]: Exception in thread "Thread-227" java.lang.IllegalArgumentException: UID segment 'Temperature_VFS/RPS_(S6)' contains invalid characters. The last segment of the channel UID must match the pattern [A-Za-z0-9_-#]*.
Jan  7 00:29:29 OpenHAB karaf[27808]: at org.eclipse.smarthome.core.thing.ChannelUID.validateSegment(ChannelUID.java:170)
Jan  7 00:29:29 OpenHAB karaf[27808]: at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:74)
Jan  7 00:29:29 OpenHAB karaf[27808]: at org.eclipse.smarthome.core.thing.ChannelUID.<init>(ChannelUID.java:48)
Jan  7 00:29:29 OpenHAB karaf[27808]: at org.openhab.binding.resol.handler.ResolBridgeHandler$1$1.packetReceived(ResolBridgeHandler.java:299)
Jan  7 00:29:29 OpenHAB karaf[27808]: at de.resol.vbus.Connection.emitHeaderReceived(Connection.java:160)
Jan  7 00:29:29 OpenHAB karaf[27808]: at de.resol.vbus.TcpConnection.runInBackground(TcpConnection.java:134)
Jan  7 00:29:29 OpenHAB karaf[27808]: at de.resol.vbus.TcpConnection.access$0(TcpConnection.java:124)
Jan  7 00:29:29 OpenHAB karaf[27808]: at de.resol.vbus.TcpConnection$1.run(TcpConnection.java:99)
Jan  7 00:29:29 OpenHAB karaf[27808]: at java.lang.Thread.run(Thread.java:745)
```
So it is clear, that there are names in the VSF, that are not legal channel names and the renaming of the channels in ResolBridgeHandler is not sufficient. We should not just replace a few explicit characters, but ensure, that only the allowed chars [A-Za-z0-9_-#] are used.

**Comment by ramack** [comment]
the "/" is still there and has to be removed, also
