### ISSUE TITLE
Crash For Time fields

### ISSUE THREAD

**Issue by ramack** [ramack/openhab2-addons#19]
Marcel Duscher [reported in the forum](https://community.openhab.org/t/new-binding-resol-vbus/2203/114):

```
Exception in thread "Thread-101" java.lang.NullPointerException
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:598)
        at de.resol.vbus.Specification.createUtcDateFormat(Specification.java:77)
        at de.resol.vbus.Specification.access$0(Specification.java:76)
        at de.resol.vbus.Specification$Formatter$2.formatTextValue(Specification.java:145)
        at de.resol.vbus.Specification.formatTextValueFromRawValueInternal(Specification.java:723)
        at de.resol.vbus.Specification.formatTextValueFromRawValue(Specification.java:738)
        at de.resol.vbus.Specification.formatTextValueFromRawValue(Specification.java:754)
        at de.resol.vbus.Specification$PacketFieldValue.formatTextValue(Specification.java:485)
        at org.openhab.binding.resol.handler.ResolBridgeHandler$1$1.packetReceived(ResolBridgeHandler.java:354)
        at de.resol.vbus.Connection.emitHeaderReceived(Connection.java:160)
        at de.resol.vbus.TcpConnection.runInBackground(TcpConnection.java:134)
        at de.resol.vbus.TcpConnection.access$0(TcpConnection.java:124)
        at de.resol.vbus.TcpConnection$1.run(TcpConnection.java:99)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ramack** [comment]
The issue seems to be related to the Time field in the data sent by the DeltaSol BX and the DeltaTherm FK.
A tentitive fix for the crash is commited in f7c69b60c38a61971670a13587f0b5fbe851538c.

We have to see whether this is useful or whether some more specific support is needed for Time and WeekTime types. Any comments or needs from users?
